[pytest]
addopts = --import-mode=importlib
testpaths =
    experiments/tests
    function-sdk-python/tests
    python-runtime/tests
    scripts/image-builder/tests
    scripts/tests
    tools/controlplane/tests
    tools/fn-init/tests
    examples/python/roman-numeral/tests
pythonpath =
    .
    function-sdk-python/src
    python-runtime/src
    scripts/image-builder
    tools/controlplane/src
    tools/fn-init/src
    examples/python/roman-numeral
