FROM node:20-alpine AS build
WORKDIR /src

{{DOCKER_SDK_COPY}}
{{DOCKER_APP_COPY}}

{{DOCKER_SDK_BUILD_BLOCK}}
WORKDIR {{DOCKER_APP_DIR}}
RUN npm install
RUN npm run build
RUN npm prune --omit=dev

FROM node:20-alpine
WORKDIR /app

{{DOCKER_FINAL_SDK_COPY}}
COPY --from=build {{DOCKER_APP_DIR}}/package.json ./package.json
COPY --from=build {{DOCKER_APP_DIR}}/node_modules ./node_modules
COPY --from=build {{DOCKER_APP_DIR}}/dist ./dist

EXPOSE 8080
CMD ["node", "dist/src/index.js"]
