FROM node:20-alpine AS build
WORKDIR /src

COPY sdks/javascript ./function-sdk-javascript
COPY functions/javascript/{{FUNCTION_NAME}} ./functions/javascript/{{FUNCTION_NAME}}

WORKDIR /src/functions/javascript/{{FUNCTION_NAME}}
RUN npm install
RUN npm run build
RUN npm prune --omit=dev

FROM node:20-alpine
WORKDIR /app

COPY --from=build /src/functions/javascript/{{FUNCTION_NAME}}/package.json ./package.json
COPY --from=build /src/functions/javascript/{{FUNCTION_NAME}}/node_modules ./node_modules
COPY --from=build /src/functions/javascript/{{FUNCTION_NAME}}/dist ./dist

EXPOSE 8080
CMD ["node", "dist/src/index.js"]
