FROM golang:1.24-alpine AS build
WORKDIR /src
COPY sdks/go /src/sdks/go
COPY functions/go/{{FUNCTION_NAME}} /src/functions/go/{{FUNCTION_NAME}}
WORKDIR /src/functions/go/{{FUNCTION_NAME}}
RUN go build -o /out/{{FUNCTION_NAME}} .

FROM alpine:3.22
WORKDIR /app
COPY --from=build /out/{{FUNCTION_NAME}} /app/{{FUNCTION_NAME}}
EXPOSE 8080
ENTRYPOINT ["/app/{{FUNCTION_NAME}}"]
